### ISSUE TITLE
menu broken

### ISSUE THREAD

**Issue by Abbe98** [Biocaching/biocaching.github.io#1]
![image](https://cloud.githubusercontent.com/assets/2631719/9293680/247ad374-4434-11e5-8342-ee1be01e38f2.png)
![image](https://cloud.githubusercontent.com/assets/2631719/9293683/3617729a-4434-11e5-9d54-0a476f172f25.png)

**Comment by Abbe98** [comment]
The new menu break point would be 1400px in the current state.

After opening the menu the user needs to move the cursor to close it again.

**Comment by pbb72** [comment]
Yes sorry, that was not tested well enough :)
