### ISSUE TITLE
Visual element for switching languages 

### ISSUE THREAD

**Issue by Abbe98** [Biocaching/biocaching.github.io#6]
Currently it's impossible for a user to switch language, we should allow this using a cookie or localStorage.

**Comment by pbb72** [comment]
We can go two ways:

1: Disable auto-redirect, and always let the user decide.

2: Store the user choice in a cookie, and prefer that value over autodetection.

**Comment by Abbe98** [comment]
My idea was something like
```
if language cookie 
  redirect
else 
  auto redirect
```
