### ISSUE TITLE
Scroll Depth Analytics is Broken

### ISSUE THREAD

**Issue by Abbe98** [Biocaching/biocaching.github.io#8]
`jQuery.scrollDepth();` returns `undefined` and no events seams to get trigged.

**Comment by Abbe98** [comment]
Ping @pbb72

**Comment by pbb72** [comment]
The ScrollDepth plugin pushes data to Google Analytics (see http://scrolldepth.parsnip.io/). It does not interact with the page.

Scroll stats can be found in GA under Behaviour > Events > Top Events > select "Event label".

To me it seems to be functioning as expected.

**Comment by Abbe98** [comment]
Found it!
